import { readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

import { getTokenRegistryJsonSchema } from '@rancard/documentation-schema';

import { getAllPages, getNavigation } from '../lib/content';
import {
  getComponentRegistry,
  getPackageRegistry,
  getTokenRegistry,
} from '../lib/registries';
import { getSearchIndex } from '../lib/search';

const repositoryRoot = path.resolve(process.cwd(), '../..');
const checkMode = process.argv.includes('--check');

const requiredAgentRule =
  'Never assume a component, property, token, or package exists unless it is present in the registry or source code.';

function json(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function withGeneratedSection(source: string, section: string): string {
  const start = '<!-- BEGIN GENERATED REPOSITORY INVENTORY -->';
  const end = '<!-- END GENERATED REPOSITORY INVENTORY -->';
  const generated = `${start}\n${section.trim()}\n${end}`;
  const pattern = new RegExp(`${start}[\\s\\S]*?${end}`);
  const next = pattern.test(source)
    ? source.replace(pattern, generated)
    : `${source.trimEnd()}\n\n${generated}`;

  return `${next.trimEnd()}\n`;
}

async function emit(relativePath: string, content: string): Promise<void> {
  const filePath = path.join(repositoryRoot, relativePath);

  if (checkMode) {
    const existing = await readFile(filePath, 'utf8').catch(() => '');
    if (existing !== content) {
      throw new Error(
        `${relativePath} is stale. Run "pnpm generate:ai" and commit the result.`,
      );
    }
    return;
  }

  await mkdir(path.dirname(filePath), { recursive: true });
  await writeFile(filePath, content);
}

const [
  pages,
  navigation,
  components,
  packages,
  tokens,
  searchIndex,
  agents,
  llms,
] = await Promise.all([
  getAllPages(),
  getNavigation(),
  getComponentRegistry(),
  getPackageRegistry(),
  getTokenRegistry(),
  getSearchIndex(),
  readFile(path.join(repositoryRoot, 'AGENTS.md'), 'utf8'),
  readFile(path.join(repositoryRoot, 'llms.txt'), 'utf8'),
]);

if (!agents.includes(requiredAgentRule)) {
  throw new Error(
    `AGENTS.md must include the required source-of-truth rule: "${requiredAgentRule}"`,
  );
}

const navigationExport = navigation.map((group) => ({
  label: group.label,
  pages: group.pages.map((page) => ({
    description: page.frontmatter.description,
    status: page.frontmatter.status,
    title: page.frontmatter.title,
    url: page.url,
  })),
}));

const inventory = `## Generated Repository Inventory

- Documentation pages: ${pages.length}
- Registered components: ${components.length}
- Registered packages: ${packages.length}
- Registered tokens: ${tokens.length}
- Search entries: ${searchIndex.length}

This inventory is derived from validated MDX and registry sources. Regenerate it with \`pnpm generate:ai\`.`;

const summary = `# Rancard Design System — AI Summary

> Generated from validated documentation and registries. Do not edit directly.

## Current scope

Phase Zero builds the documentation and engineering platform. Production tokens, stable component APIs, Figma assets, and package publication remain prohibited.

## Verified inventory

- Documentation pages: ${pages.length}
- Registered components: ${components.length}
- Registered packages: ${packages.length}
- Registered tokens: ${tokens.length}
- Search entries: ${searchIndex.length}

## Source-of-truth rule

${requiredAgentRule}

## Lifecycle

Planned → Experimental → Alpha → Beta → Stable → Deprecated → Removed
`;

const contributionRules = `# AI Contribution Rules

> Generated repository context. Do not edit directly.

- Work only within the active implementation phase.
- Read \`AGENTS.md\`, \`CLAUDE.md\`, \`llms.txt\`, accepted ADRs, and the planning documents before architectural work.
- ${requiredAgentRule}
- Do not define final tokens, stable component APIs, production Figma assets, or publish packages during Phase Zero.
- Use only the \`--docs-*\` namespace for temporary documentation styles.
- Validate formatting, lint, types, tests, builds, content, registries, links, and accessibility as applicable.
- Add or update an ADR before changing a major architectural decision.
`;

const fullContext = `# Rancard Design System — Full AI Context

> Generated by \`pnpm generate:ai\` from validated repository data. Do not edit directly.

${summary.replace('# Rancard Design System — AI Summary', '## AI Summary').replace(/\n## /g, '\n### ')}

## Documentation navigation

${navigationExport
  .map(
    (group) =>
      `### ${group.label}\n\n${group.pages
        .map(
          (page) =>
            `- [${page.title}](${page.url}) — ${page.status}: ${page.description}`,
        )
        .join('\n')}`,
  )
  .join('\n\n')}

## Registered components

${
  components.length === 0
    ? '- None.'
    : components
        .map(
          (component) =>
            `- ${component.displayName} (${component.name}) — ${component.status}; documentation: ${component.documentation}`,
        )
        .join('\n')
}

## Registered packages

${packages
  .map(
    (packageEntry) =>
      `- ${packageEntry.name} — ${packageEntry.status}; ${
        packageEntry.private ? 'private' : 'public'
      }`,
  )
  .join('\n')}

## Registered tokens

${
  tokens.length === 0
    ? '- None. Do not infer token names or values.'
    : tokens.map((token) => `- ${token.name} — ${token.status}`).join('\n')
}
`;

await Promise.all([
  emit('AGENTS.md', withGeneratedSection(agents, inventory)),
  emit('llms.txt', withGeneratedSection(llms, inventory)),
  emit('apps/docs/public/ai/navigation.json', json(navigationExport)),
  emit('apps/docs/public/ai/component-registry.json', json(components)),
  emit('apps/docs/public/ai/package-registry.json', json(packages)),
  emit('apps/docs/public/ai/token-registry.json', json(tokens)),
  emit(
    'apps/docs/public/ai/token-schema.json',
    json(getTokenRegistryJsonSchema()),
  ),
  emit('apps/docs/public/ai/search-index.json', json(searchIndex)),
  emit('apps/docs/public/ai/design-system-summary.md', summary),
  emit('apps/docs/public/ai/contribution-rules.md', contributionRules),
  emit('llms-full.txt', fullContext),
]);

process.stdout.write(
  `${checkMode ? 'Validated' : 'Generated'} 11 AI context artifacts from ${pages.length} pages, ${components.length} ${components.length === 1 ? 'component' : 'components'}, ${packages.length} packages, and ${tokens.length} tokens.\n`,
);
